name: Deploy to GCP

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/169596900841/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'ecommerce-deploy@e-commerce-petproject.iam.gserviceaccount.com'
          token_format: 'urn:ietf:params:oauth:token-type:id_token'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Google Cloud project
        run: |
          gcloud config set project ecommerce-petproject
          gcloud config set compute/zone asia-southeast1-a

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/ecommerce-petproject/ecommerce-app:latest

      - name: Deploy to GCE
        run: |
          gcloud compute instances update-container ecommerce-vm \
            --container-image gcr.io/ecommerce-petproject/ecommerce-app:latest \
            --zone asia-southeast1-a