name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Google Cloud project
        run: |
          gcloud config set project E-Commerce PetProject
          gcloud config set compute/zone asia-southeast1-a

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/e-commerce-petproject/ecommerce-app:latest

      - name: Deploy to GCE
        run: |
          gcloud compute instances update-container ecommerce-vm \
            --container-image gcr.io/e-commerce-petproject/ecommerce-app:latest \
            --zone asia-southeast1-a