name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: principalSet://iam.googleapis.com/projects/169596900841/locations/global/workloadIdentityPools/github-actions-pool/attribute.repository/isverbitskiy/ecommerce

      - name: Configure Google Cloud project
        run: |
          gcloud config set project e-commerce-petproject
          gcloud config set compute/zone asia-southeast1-a

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gcr.io/e-commerce-petproject/ecommerce-app:latest

      - name: Deploy to GCE
        run: |
          gcloud compute instances update-container ecommerce-vm \
            --container-image gcr.io/e-commerce-petproject/ecommerce-app:latest \
            --zone asia-southeast1-a
