name: Deploy to GCP

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          token_format: 'access_token'
          create_credentials_file: true
          audience: 'https://github.com/isverbitskiy/ecommerce'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker gcr.io --quiet

      - name: Build and push Docker image
        env:
          GCR_HOSTNAME: gcr.io
        run: |
          docker build -t $GCR_HOSTNAME/${{ secrets.GCP_PROJECT_ID }}/ecommerce-app:${{ github.sha }} .
          docker push $GCR_HOSTNAME/${{ secrets.GCP_PROJECT_ID }}/ecommerce-app:${{ github.sha }}

      - name: Deploy to GCE
        run: |
          gcloud compute instances update-container ecommerce-instance \
            --container-image=$GCR_HOSTNAME/${{ secrets.GCP_PROJECT_ID }}/ecommerce-app:${{ github.sha }} \
            --zone=asia-southeast1-a