name: Deploy to GCP

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: 'latest'

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/169596900841/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: ecommerce-deploy@e-commerce-petproject.iam.gserviceaccount.com
          token_format: urn:ietf:params:oauth:token-type:id_token
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          id_token_include_email: false

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$PROJECT_ID/ecommerce-app .
          docker push gcr.io/$PROJECT_ID/ecommerce-app

      - name: Deploy to GCE
        run: |
          gcloud compute instances update-container ecommerce-instance \
            --container-image=gcr.io/$PROJECT_ID/ecommerce-app \
            --zone=asia-southeast1-a